//Create user
POST http://localhost:5000/users 
Content-Type: application/json

{
    "name": "Ana",
    "email": "ana123@gmail.com",
    "password": "hamster",
    "confPassword": "hamster",
    "role": "admin"
}
###
//get all users
GET http://localhost:5000/users 
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJVc2VySW5mbyI6eyJ1c2VySWQiOiJjNmJmMjI3OC01Mjk3LTQ0YjItOTU1My01ODhlOGRkNjcwYjYiLCJyb2xlIjoicHJvZmVzc29yIn0sImlhdCI6MTczNjU5NzczOCwiZXhwIjoxNzM2NTk3NzY4fQ.7BoNqrrgE3IhlY_vSk3F8iGbiMhlIMZzg1E-Hybaekw
###
//get single user
GET http://localhost:5000/users/dfe85a26-447a-41af-ab61-1e8e079b1bcf
###
//update user
PATCH http://localhost:5000/users/dfe85a26-447a-41af-ab61-1e8e079b1bcf 
Content-Type: application/json

{
    "name": "Nume nou",
    "email": "testabc@gmail.com",
    "password": "",
    "confPassword": "",
    "role": "professor"
}
###
//delete user
DELETE http://localhost:5000/users/3619548c-b42a-4d02-87f2-60f95680895d
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJVc2VySW5mbyI6eyJ1c2VySWQiOiI1MDAwZjcyMS00NjAxLTQ1YjAtYWQyZi1iOGEzM2ZiMDgzNmMiLCJyb2xlIjoiYWRtaW4ifSwiaWF0IjoxNzM2NTk3NjgwLCJleHAiOjE3MzY1OTc3MTB9.Px5JlQOWuICxD1L3vK1_1CK4uF825yCkhGhWc1QsHSw

###
//Login profesor user
POST http://localhost:5000/login
Content-Type: application/json

{
    "email": "dascalescugabi03@yahoo.ro",
    "password": "caini"
}
###
//Login admin user
POST http://localhost:5000/login
Content-Type: application/json

{
    "email": "balintfranceska@gmail.com",
    "password": "pisici"
}
###
//Logout admin
GET http://localhost:5000/logout
###
//Refresh token
GET http://localhost:5000/refresh