//Create user
POST http://localhost:5000/users 
Content-Type: application/json

{
    "name": "Gabi",
    "email": "gabi@gmail.com",
    "password": "caini",
    "confPassword": "caini",
    "role": "professor"
}
###
//get all users
GET http://localhost:5000/users 
###
//get single user
GET http://localhost:5000/users/dfe85a26-447a-41af-ab61-1e8e079b1bcf
###
//update user
PATCH http://localhost:5000/users/dfe85a26-447a-41af-ab61-1e8e079b1bcf 
Content-Type: application/json

{
    "name": "Nume nou",
    "email": "testabc@gmail.com",
    "password": "",
    "confPassword": "",
    "role": "professor"
}
###
//delete user
DELETE http://localhost:5000/users/82bfe9fd-aa4f-402f-b311-ab6e3bdf2e57

###
//Login profesor user
POST http://localhost:5000/login
Content-Type: application/json

{
    "email": "gabi@gmail.com",
    "password": "caini"
}
###
//Login admin user
POST http://localhost:5000/login
Content-Type: application/json

{
    "email": "balintfranceska@gmail.com",
    "password": "pisici"
}
###
//Get logged user
GET http://localhost:5000/me
###
//Logout admin
DELETE http://localhost:5000/logout